name: Trigger milvus.io publish every time

on:
  repository_dispatch:
    types: prod-deploy
  push:
    branches:
      - master

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      # - name: Stats Docs Words
      #   env: 
      #     MSERVICE_URL: ${{secrets.MSERVICE_URL}}
      #   run: |
      #     mv word-count.md word-count.js
      #     yarn
      #     node word-count.js

      - name: Trigger milvus.io
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          mv trigger-milvus-build.md trigger-milvus-build.js
          yarn
          node trigger-milvus-build.js
